version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: auth-test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: auth-db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: 'postgres-db'
    ports:
      - 8080:8080

  server:
    build: .
    command: npm run start
    volumes:
      - .:/app
    restart: always
    container_name: server-app
    ports:
      - 3033:3000
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://auth-test:test@postgres/auth-db
    env_file:
      - ./.env

volumes:
  postgres_data:
